name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  sqlite:
    name: Ruby ${{ matrix.ruby }} on Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        rails: ['6.0', '6.1', '7.0']

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
          rubygems: latest

      - name: Run tests
        env:
          DATABASE_URL: "sqlite3:hashed_ids_test"
          RAILS_ENV: test
        run: |
          bundle exec rails db:test:prepare
          bundle exec rails test

